repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --ignore=E402]
        files: \.(py)$
        types: [python]
        exclude: ^tests/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: \.(py)$
        types: [python]
        exclude: ^tests/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--ignore=E501,W503,E402,F401']
        files: \.(py)$
        types: [python]
        exclude: ^tests/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/
      - id: end-of-file-fixer
        exclude: ^tests/
      - id: check-yaml
      - id: check-added-large-files
