repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: rust-build
        name: Rust build
        entry: bash -c "cd library && cargo build --release"
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^library/

      - id: rust-test
        name: Rust test
        entry: bash -c "cd library && cargo test --release"
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^library/

      - id: zig-build
        name: Zig build
        entry: bash -c "cd cli && zig build"
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^cli/
